INSERT INTO authors ("name", "wikidata_id")
VALUES
    ('Agatha Christie', 'Q35064'),
    ('Isaac Asimov', 'Q34981'),
    ('Toni Morrison', 'Q72334'),
    ('Ursula K. Le Guin', 'Q181659'),
    ('Kurt Vonnegut', 'Q49074'),
    ('Haruki Murakami', 'Q134798'),
    ('Jane Austen', 'Q36322'),
    ('Gabriel García Márquez', 'Q5878'),
    ('George Orwell', 'Q3335'),
    ('Virginia Woolf', 'Q40909'),
    ('Ray Bradbury', 'Q40640'),
    ('Margaret Atwood', 'Q183492'),
    ('F. Scott Fitzgerald', 'Q93354'),
    ('Chimamanda Ngozi Adichie', 'Q230141'),
    ('James Baldwin', 'Q273210'),
    ('Salman Rushdie', 'Q44306'),
    ('Charlotte Brontë', 'Q127332'),
    ('Mark Twain', 'Q7245'),
    ('George R. R. Martin', 'Q181677'),
    ('Terry Pratchett', 'Q46248'),
    ('Stephen King', 'Q39829'),
    ('Aldous Huxley', 'Q81447'),
    ('Homer H. Hickam', 'Q1626025'),
    ('Mary Shelley', 'Q47152'),
    ('Leo Tolstoy', 'Q7243'),
    ('Nora Roberts', 'Q231356'),
    ('Douglas Adams', 'Q42'),
    ('Ian McEwan', 'Q190379'),
    ('Octavia E. Butler', 'Q239739'),
    ('Khaled Hosseini', 'Q193116');

INSERT INTO books("title", "author_id")
VALUES
    ('Murder on the Orient Express', 1),
    ('And Then There Were None', 1),
    ('The Murder of Roger Ackroyd', 1),
    ('Foundation', 2),
    ('I, Robot', 2),
    ('The Caves of Steel', 2),
    ('Beloved', 3),
    ('Song of Solomon', 3),
    ('The Bluest Eye', 3),
    ('A Wizard of Earthsea', 4),
    ('The Left Hand of Darkness', 4),
    ('The Dispossessed', 4),
    ('Slaughterhouse-Five', 5),
    ('Cat''s Cradle', 5),
    ('Breakfast of Champions', 5),
    ('Norwegian Wood', 6),
    ('Kafka on the Shore', 6),
    ('1Q84', 6),
    ('Pride and Prejudice', 7),
    ('Emma', 7),
    ('Sense and Sensibility', 7),
    ('One Hundred Years of Solitude', 8),
    ('Love in the Time of Cholera', 8),
    ('Chronicle of a Death Foretold', 8),
    ('1984', 9),
    ('Animal Farm', 9),
    ('Homage to Catalonia', 9),
    ('Mrs Dalloway', 10),
    ('To the Lighthouse', 10),
    ('A Room of One''s Own', 10),
    ('Fahrenheit 451', 11),
    ('The Martian Chronicles', 11),
    ('Dandelion Wine', 11),
    ('The Handmaid''s Tale', 12),
    ('Oryx and Crake', 12),
    ('The Testaments', 12),
    ('The Great Gatsby', 13),
    ('Tender Is the Night', 13),
    ('This Side of Paradise', 13),
    ('Americanah', 14),
    ('Half of a Yellow Sun', 14),
    ('Purple Hibiscus', 14),
    ('Go Tell It on the Mountain', 15),
    ('The Fire Next Time', 15),
    ('Giovanni''s Room', 15),
    ('Midnight''s Children', 16),
    ('The Satanic Verses', 16),
    ('Shame', 16),
    ('Jane Eyre', 17),
    ('Villette', 17),
    ('The Professor', 17),
    ('Adventures of Huckleberry Finn', 18),
    ('The Adventures of Tom Sawyer', 18),
    ('A Connecticut Yankee in King Arthur''s Court', 18),
    ('A Game of Thrones', 19),
    ('A Clash of Kings', 19),
    ('A Storm of Swords', 19),
    ('The Shining', 21),
    ('It', 21),
    ('Misery', 21),
    ('Brave New World', 22),
    ('Island', 22),
    ('Eyeless in Gaza', 22),
    ('The Iliad', 23),
    ('The Odyssey', 23),
    ('The Iliad and The Odyssey', 23),
    ('Frankenstein', 24),
    ('The Last Man', 24),
    ('Mathilda', 24),
    ('War and Peace', 25),
    ('Anna Karenina', 25),
    ('The Death of Ivan Ilyich', 25),
    ('The Hollow', 26),
    ('Vision in White', 26),
    ('The Search', 26),
    ('Atonement', 28),
    ('Amsterdam', 28),
    ('Enduring Love', 28),
    ('Kindred', 29),
    ('Parable of the Sower', 29),
    ('Dawn', 29),
    ('The Kite Runner', 30),
    ('A Thousand Splendid Suns', 30),
    ('And the Mountains Echoed', 30),
    ('The Mystery of the Blue Train', 1),
    ('Death on the Nile', 1),
    ('Pebble in the Sky', 2),
    ('The Naked Sun', 2),
    ('Tar Baby', 3),
    ('Paradise', 3),
    ('Tehanu', 4),
    ('Earthsea', 4),
    ('God Bless You, Mr. Rosewater', 5),
    ('Hard-Boiled Wonderland and the End of the World', 6),
    ('After Dark', 6),
    ('Mansfield Park', 7),
    ('Northanger Abbey', 7),
    ('Memories of My Melancholy Whores', 6),
    ('The Autumn of the Patriarch', 8),
    ('The General in His Labyrinth', 8),
    ('Keep the Aspidistra Flying', 9),
    ('Orlando', 10),
    ('Something Wicked This Way Comes', 11),
    ('The Year of the Flood', 12),
    ('Winter Dreams', 13),
    ('We Should All Be Feminists', 14),
    ('If Beale Street Could Talk', 15),
    ('Shalimar the Clown', 16),
    ('The Tenant of Wildfell Hall', 17),
    ('Pudd''nhead Wilson', 18),
    ('A Feast for Crows', 19),
    ('Carrie', 21),
    ('Brave New World Revisited', 22),
    ('The Screenplay of The Odyssey', 23),
    ('Proserpine', 24),
    ('Childhood', 25),
    ('The Search', 26),
    ('Saturday', 28),
    ('Fledgling', 29),
    ('Sea Prayer', 30),
    ('The Silmarillion', 2),
    ('The Wonderful Wizard of Oz', 18),
    ('The Portable Aeschylus', 23),
    ('The God of Small Things', 14),
    ('The Bell Jar', 10),
    ('The Gunslinger', 19),
    ('Nineteen Eighty-Four', 9),
    ('The Handmaid''s Tale: TV Tie-in', 12),
    ('The Chronicles of Narnia', 18),
    ('The Poisonwood Bible', 14),
    ('House of Leaves', 21),
    ('The Road', 12),
    ('The Night Circus', 6),
    ('The Plot', 26),
    ('A Study in Scarlet', 1),
    ('A Dance with Dragons', 19);
